palette = "carbonfox"

[character]
vimcmd_replace_one_symbol = '[r](bold green)'
vimcmd_replace_symbol = '[R](bold green)'
vimcmd_visual_symbol = '[V](bold yellow)'

[hostname]
ssh_symbol = ''

[shlvl]
disabled = false
symbol = ""

# [metadata]
# name = "carbonfox"
# author = "wjohnsto"
# origin_url = "https://github.com/EdenEast/nightfox.nvim"
[palettes.carbonfox]
red = "#ee5396"
green = "#25be6a"
purple = "#be95ff"
yellow = "#08bdba"
os_bg = "#7b7c7e"
os_fg = "#0c0c0c"
dir_bg = "#25be6a"
dir_fg = "#161616"
git_bg = "#08bdba"
git_fg = "#252525"
lang_bg = "#78a9ff"
lang_fg = "#353535"
